old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    
    producers:
        emailing:
            connection: default
            exchange_options:
                name: emails
                type: direct
    
    consumers:
        emailing:
            connection: default
            exchange_options: { name: 'emails', type: direct}
            queue_options: { name: 'emails'}
            callback: email_service